# PyTorch张量的运算API(上)

来自b站up主deep_thoughts 合集【PyTorch源码教程与前沿人工智能算法复现讲解】

P_02_PyTorch张量的运算API(上)：
    
https://www.bilibili.com/video/BV1wQ4y1q7Bm/?spm_id_from=333.788&vd_source=18e91d849da09d846f771c89a366ed40

### 将张量分割成特定数目

In [2]:
import torch

b = torch.rand([3,2])
print(b)

c, d = torch.chunk(b, chunks=2)
print(c)
print(d)

c, d = torch.chunk(b, chunks=2, dim=1)
print(c)
print(d)

tensor([[0.8075, 0.4487],
        [0.6549, 0.2947],
        [0.5258, 0.2786]])
tensor([[0.8075, 0.4487],
        [0.6549, 0.2947]])
tensor([[0.5258, 0.2786]])
tensor([[0.8075],
        [0.6549],
        [0.5258]])
tensor([[0.4487],
        [0.2947],
        [0.2786]])


### 沿着某一维取变量

In [6]:
t = torch.tensor([[1, 2], [3, 4]])
print(t)

print(torch.gather(t, 1, torch.tensor([[0, 0], [1, 0]])))

tensor([[1, 2],
        [3, 4]])
tensor([[1, 1],
        [4, 3]])


### reshape

In [8]:
a = torch.arange(4.)
print(a)

print(torch.reshape(a, (2, 2)))

b = torch.tensor([[0, 1], [2, 3]])
print(b)
print(torch.reshape(b, (-1,)))

tensor([0., 1., 2., 3.])
tensor([[0., 1.],
        [2., 3.]])
tensor([[0, 1],
        [2, 3]])
tensor([0, 1, 2, 3])


### scatter

self[index[i][j][k]][j][k] = src[i][j][k]  # if dim == 0

self[i][index[i][j][k]][k] = src[i][j][k]  # if dim == 1

self[i][j][index[i][j][k]] = src[i][j][k]  # if dim == 2

In [11]:
src = torch.arange(1, 11).reshape((2, 5))
print(src)

index = torch.tensor([[0, 1, 2, 0]])
a = torch.zeros(3, 5, dtype=src.dtype)
b = torch.zeros(3, 5, dtype=src.dtype)
a.scatter_(0, index, src)  # 带_是原位操作
print(a)
b.scatter(0, index, src)  # 不带_非原位操作
print(b)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])
tensor([[1, 0, 0, 4, 0],
        [0, 2, 0, 0, 0],
        [0, 0, 3, 0, 0]])
tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])


### scatter_add

self[index[i][j][k]][j][k] += src[i][j][k]  # if dim == 0

self[i][index[i][j][k]][k] += src[i][j][k]  # if dim == 1

self[i][j][index[i][j][k]] += src[i][j][k]  # if dim == 2

In [13]:
# tensor.scatter_add_(0, index, src)

### split

In [15]:
a = torch.arange(10).reshape(5,2)
print(a)

print(torch.split(a,2))

print(torch.split(a, [1,4]))

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
(tensor([[0, 1],
        [2, 3]]), tensor([[4, 5],
        [6, 7]]), tensor([[8, 9]]))
(tensor([[0, 1]]), tensor([[2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]))


### squeeze 对维度为1的进行压缩

In [22]:
print(a.shape)

a = torch.reshape(a, [5,1,2])
print(a.shape)

a = torch.squeeze(a)
print(a.shape)

torch.Size([5, 2])
torch.Size([5, 1, 2])
torch.Size([5, 2])


In [24]:
a = torch.reshape(a, [5,1,2,1,1])
print(a.shape)

a = torch.squeeze(a, dim=1)
print(a.shape)

torch.Size([5, 1, 2, 1, 1])
torch.Size([5, 2, 1, 1])


### stack 沿着某一个新的维度拼接张量

In [27]:
a = torch.rand([3, 2])

b = torch.rand([3, 2])

print(torch.stack([a,b]))
print(torch.stack([a,b]).shape)

print(torch.stack([a,b],dim=1))
print(torch.stack([a,b],dim=1).shape)

tensor([[[0.4368, 0.3750],
         [0.4409, 0.6027],
         [0.0223, 0.3677]],

        [[0.3348, 0.8039],
         [0.4344, 0.9419],
         [0.5585, 0.0271]]])
torch.Size([2, 3, 2])
tensor([[[0.4368, 0.3750],
         [0.3348, 0.8039]],

        [[0.4409, 0.6027],
         [0.4344, 0.9419]],

        [[0.0223, 0.3677],
         [0.5585, 0.0271]]])
torch.Size([3, 2, 2])
