# PyTorch张量的运算API(下)

来自b站up主deep_thoughts 合集【PyTorch源码教程与前沿人工智能算法复现讲解】

P_03_PyTorch张量的运算API(下)：
    
https://www.bilibili.com/video/BV1Hq4y1R7dM/?spm_id_from=333.788&vd_source=18e91d849da09d846f771c89a366ed40

### 数据类型

### take

把张量看作一维张量，按一维索引寻找

In [1]:
import torch

src = torch.tensor([[4, 3, 5],
                    [6, 7, 8]])

print(torch.take(src, torch.tensor([0, 2, 5])))

tensor([4, 5, 8])


### tile
拷贝

In [3]:
x = torch.tensor([1, 2, 3])
print(x.tile((2,)))

y = torch.tensor([[1, 2], [3, 4]])
print(y.shape)
print(y.tile((2,2)))
print(y.tile((2,2)).shape)

tensor([1, 2, 3, 1, 2, 3])
torch.Size([2, 2])
tensor([[1, 2, 1, 2],
        [3, 4, 3, 4],
        [1, 2, 1, 2],
        [3, 4, 3, 4]])
torch.Size([4, 4])


In [4]:
a = torch.rand((4,3))
a_tiled = torch.tile(a, [2, 1])
print(a_tiled)
a_tiled = torch.tile(a, [1, 3])
print(a_tiled)
a_tiled = torch.tile(a, [2, 3])
print(a_tiled)

tensor([[0.9383, 0.8079, 0.2456],
        [0.5641, 0.4005, 0.6228],
        [0.0807, 0.4719, 0.7719],
        [0.8106, 0.9535, 0.2595],
        [0.9383, 0.8079, 0.2456],
        [0.5641, 0.4005, 0.6228],
        [0.0807, 0.4719, 0.7719],
        [0.8106, 0.9535, 0.2595]])
tensor([[0.9383, 0.8079, 0.2456, 0.9383, 0.8079, 0.2456, 0.9383, 0.8079, 0.2456],
        [0.5641, 0.4005, 0.6228, 0.5641, 0.4005, 0.6228, 0.5641, 0.4005, 0.6228],
        [0.0807, 0.4719, 0.7719, 0.0807, 0.4719, 0.7719, 0.0807, 0.4719, 0.7719],
        [0.8106, 0.9535, 0.2595, 0.8106, 0.9535, 0.2595, 0.8106, 0.9535, 0.2595]])
tensor([[0.9383, 0.8079, 0.2456, 0.9383, 0.8079, 0.2456, 0.9383, 0.8079, 0.2456],
        [0.5641, 0.4005, 0.6228, 0.5641, 0.4005, 0.6228, 0.5641, 0.4005, 0.6228],
        [0.0807, 0.4719, 0.7719, 0.0807, 0.4719, 0.7719, 0.0807, 0.4719, 0.7719],
        [0.8106, 0.9535, 0.2595, 0.8106, 0.9535, 0.2595, 0.8106, 0.9535, 0.2595],
        [0.9383, 0.8079, 0.2456, 0.9383, 0.8079, 0.2456, 0.9383, 0.807

### transpose
交换维度

In [7]:
print(a.shape)
print(torch.transpose(a, 0, 1).shape)
print(torch.transpose(a, 1, 0).shape)  # 交换维度次序无影响

torch.Size([4, 3])
torch.Size([3, 4])
torch.Size([3, 4])


### unbind

In [9]:
print(torch.unbind(a, dim=0))
print(torch.unbind(a, dim=1))

(tensor([0.9383, 0.8079, 0.2456]), tensor([0.5641, 0.4005, 0.6228]), tensor([0.0807, 0.4719, 0.7719]), tensor([0.8106, 0.9535, 0.2595]))
(tensor([0.9383, 0.5641, 0.0807, 0.8106]), tensor([0.8079, 0.4005, 0.4719, 0.9535]), tensor([0.2456, 0.6228, 0.7719, 0.2595]))


In [10]:
a = torch.rand((2,3,4))
print(a)

print(torch.unbind(a, dim=0))
print(torch.unbind(a, dim=1))
print(torch.unbind(a, dim=2))

tensor([[[0.7802, 0.2730, 0.2307, 0.1328],
         [0.4724, 0.8309, 0.6556, 0.3949],
         [0.3529, 0.0505, 0.1186, 0.0256]],

        [[0.2904, 0.7528, 0.3549, 0.5706],
         [0.7978, 0.8344, 0.7013, 0.3854],
         [0.1777, 0.4671, 0.8260, 0.3666]]])
(tensor([[0.7802, 0.2730, 0.2307, 0.1328],
        [0.4724, 0.8309, 0.6556, 0.3949],
        [0.3529, 0.0505, 0.1186, 0.0256]]), tensor([[0.2904, 0.7528, 0.3549, 0.5706],
        [0.7978, 0.8344, 0.7013, 0.3854],
        [0.1777, 0.4671, 0.8260, 0.3666]]))
(tensor([[0.7802, 0.2730, 0.2307, 0.1328],
        [0.2904, 0.7528, 0.3549, 0.5706]]), tensor([[0.4724, 0.8309, 0.6556, 0.3949],
        [0.7978, 0.8344, 0.7013, 0.3854]]), tensor([[0.3529, 0.0505, 0.1186, 0.0256],
        [0.1777, 0.4671, 0.8260, 0.3666]]))
(tensor([[0.7802, 0.4724, 0.3529],
        [0.2904, 0.7978, 0.1777]]), tensor([[0.2730, 0.8309, 0.0505],
        [0.7528, 0.8344, 0.4671]]), tensor([[0.2307, 0.6556, 0.1186],
        [0.3549, 0.7013, 0.8260]]), tensor([[0.

### unsqueeze
在特定维度上新增维度

In [16]:
print(a.shape)
print(torch.unsqueeze(a, dim=0).shape)
print(torch.unsqueeze(a, dim=1).shape)
print(torch.unsqueeze(a, dim=-1).shape)

torch.Size([2, 3, 4])
torch.Size([1, 2, 3, 4])
torch.Size([2, 1, 3, 4])
torch.Size([2, 3, 4, 1])


### where
根据条件返回

In [17]:
a = torch.rand(2,2)
b = torch.zeros_like(a)

print(a)
print(torch.where(a>0.5,a,b))

tensor([[0.4035, 0.6078],
        [0.4278, 0.5887]])
tensor([[0.0000, 0.6078],
        [0.0000, 0.5887]])


### 随机种子

In [38]:
# torch.manual_seed(args.seed)

### 伯努利随机
按概率生成0 1

In [18]:
a = torch.empty(3, 3).uniform_(0, 1)  # generate a uniform random matrix with range [0, 1]
print(a)

print(torch.bernoulli(a))

tensor([[0.7856, 0.9535, 0.5887],
        [0.1322, 0.3555, 0.8761],
        [0.1007, 0.1046, 0.2710]])
tensor([[1., 1., 0.],
        [1., 0., 1.],
        [0., 0., 0.]])


### 正态分布

In [19]:
# 按不同均值 不同方差产生
print(torch.normal(mean=torch.arange(1., 11.), std=torch.arange(1, 0, -0.1)))

# 按同一均值 不同方差产生
print(torch.normal(mean=0.5, std=torch.arange(1, 6.)))

# 均值标准差给定 指定生成大小
print(torch.normal(2, 3, size=(1, 4)))

tensor([1.3837, 2.4091, 3.0886, 3.7870, 4.7371, 5.9627, 7.2222, 7.8592, 8.8449,
        9.8328])
tensor([ 2.0447,  3.3631,  9.7270,  3.2062, -2.3890])
tensor([[-3.8883,  5.9997,  2.6758,  3.2884]])


### rand
0-1区间均匀分布 [0, 1)

### randint
随机生成整数 指定上下界和大小

In [35]:
# 指定上下界
print(torch.randint(3, 5, (3,)))

# 指定上界
print(torch.randint(10, (2, 2)))

tensor([3, 4, 4])
tensor([[3, 5],
        [4, 6]])


### randn
均值为0 标准差为1的正态分布

In [36]:
print(torch.randn(4))

print(torch.randn(2, 3))

tensor([0.7700, 0.2252, 1.4954, 1.4723])
tensor([[ 0.7366, -0.5231,  1.5348],
        [ 0.3197,  1.3643, -0.2376]])


### randperm
获取随机组合,用于构建随机数据集索引

In [37]:
print(torch.randperm(4))

tensor([1, 0, 2, 3])
