# PyTorch_nnConv2d卷积网络使用教程

来自b站up主deep_thoughts 合集【PyTorch源码教程与前沿人工智能算法复现讲解】

P_22_PyTorch_nnConv2d卷积网络使用教程：
    
https://www.bilibili.com/video/BV1644y1h7LN/?spm_id_from=333.788&vd_source=18e91d849da09d846f771c89a366ed40

torch.nn.Conv2d 官方文档：https://pytorch.org/docs/stable/generated/torch.nn.Conv2d.html#torch.nn.Conv2d

## 二维卷积代码演示

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

in_channels = 1
out_channels = 1
kernel_size = 3
batch_size = 1
bias = False
input_size = [batch_size, in_channels, 4, 4]

conv_layer = torch.nn.Conv2d(in_channels, out_channels, kernel_size, bias=bias)
input_feature_map = torch.randn(input_size)
output_feature_map = conv_layer(input_feature_map)

print(input_feature_map)
print(conv_layer.weight)  # 1*1*3*3=out_channels*in_channels*height*width
print(output_feature_map)

tensor([[[[-1.6155, -0.9003, -1.2621,  0.3788],
          [-0.4390,  0.8870,  0.4498,  0.2923],
          [-0.6850,  0.1102,  1.1019,  0.8104],
          [-1.5448,  1.4200,  1.3042,  1.1856]]]])
Parameter containing:
tensor([[[[ 0.0935, -0.0714,  0.2275],
          [-0.1964, -0.2870, -0.0367],
          [-0.1168,  0.2220,  0.0298]]]], requires_grad=True)
tensor([[[[-0.4214,  0.0339],
          [ 0.5949, -0.0914]]]], grad_fn=<ConvolutionBackward0>)


## functional.conv2d演示
需要手动传入权重

In [2]:
output_feature_map1 = F.conv2d(input_feature_map, conv_layer.weight)
print(output_feature_map1)

tensor([[[[-0.4214,  0.0339],
          [ 0.5949, -0.0914]]]], grad_fn=<ConvolutionBackward0>)
